### ISSUE TITLE
jinja2.exceptions.UndefinedError: 'period' is undefined in period_archives.html

### ISSUE THREAD

**Issue by arulrajnet** [duilio/pelican-octopress-theme#77]
Not able to generate html while running pelican command

`pelican --debug --autoreload -r content -o output -s pelicanconf.py -t pelican-octopress-theme`

Environmental

Ubuntu `14.04.2 LTS`
Python `2.7.6`
Pelican `3.3.0`
Jinja2 `2.7.3`

The error log is 

```
CRITICAL: ("'period' is undefined",)
CRITICAL: 'period' is undefined
Traceback (most recent call last):
  File "/usr/bin/pelican", line 9, in <module>
    load_entry_point('pelican==3.3', 'console_scripts', 'pelican')()
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 350, in main
    pelican.run()
  File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 181, in run
    p.generate_output(writer)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 475, in generate_output
    self.generate_pages(writer)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 370, in generate_pages
    self.generate_period_archives(write)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 303, in generate_period_archives
    _generate_period_archives(self.dates, key, save_as)
  File "/usr/lib/python2.7/dist-packages/pelican/generators.py", line 285, in _generate_period_archives
    dates=archive, blog=True)
  File "/usr/lib/python2.7/dist-packages/pelican/writers.py", line 211, in write_file
    override_output)
  File "/usr/lib/python2.7/dist-packages/pelican/writers.py", line 148, in _write_file
    output = template.render(localcontext)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/workspace/others/arulrajnet/blog/arulraj.net/pelican-octopress-theme/templates/period_archives.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/opt/workspace/others/arulrajnet/blog/arulraj.net/pelican-octopress-theme/templates/base.html", line 11, in top-level template code
    <title>{% block title %}{{ SITENAME }}{% endblock %}</title>
  File "/opt/workspace/others/arulrajnet/blog/arulraj.net/pelican-octopress-theme/templates/period_archives.html", line 2, in block "title"
    {% block title %}Archive &ndash; {{ period[2] }} {{ period[1] }} {{ period[0]  }} &mdash; {{ SITENAME }}{% endblock %}
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 378, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'period' is undefined
```

**Comment by arulrajnet** [comment]
Update pelican to 3.5.0 version is fixed that issue.

`sudo pip install --upgrade pelican`
